# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main" ]
  create:
    tags: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client-pwa

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Environment Variables
        run: echo "${{ vars.ENV }}" >> .env
        working-directory: ./client-pwa

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: ./client-pwa

      - name: Build App
        run: node_modules/.bin/vite build
        working-directory: ./client-pwa

      - name: Compress Build Artifacts
        run: tar -czf build-artifacts.tar.gz build package.json package-lock.json node_modules
        working-directory: ./client-pwa

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
         name: build-artifacts
         path: ./client-pwa/build-artifacts.tar.gz

  deploy:

    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Download Build App
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build # downloaded artifact will be stored here

      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ vars.PRODUCTION_SERVER_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy to Production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PRODUCTION_SERVER_URI: ${{ vars.PRODUCTION_SERVER_URI }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key build/build-artifacts.tar.gz ${PRODUCTION_SERVER_URI}:/opt/vendo_report
          ssh -i ssh_key ${PRODUCTION_SERVER_URI} "cd /opt/vendo_report && tar -xzf build-artifacts.tar.gz && pm2 restart pwifi"
